### ISSUE TITLE
Template - CSV file to Json file

### ISSUE THREAD

**Issue by davegroberts** [FrendsPlatform/FrendsTemplates#8]
This process will take the contents of a file. It will convert the CSV data into Json format and then write the converted data to a Json file. 

- [ ] test

**Comment by davegroberts** [comment]
Design document.

[Template - Json file to CSV file.docx](https://github.com/FrendsPlatform/FrendsTemplates/files/14739370/Template.-.Json.file.to.CSV.file.docx)

**Comment by davegroberts** [comment]
Developement complete ready for review

**Comment by jannejjj** [comment]
There is a bug with the SFTP upload task which makes it throw an exception if the write behavior has been set to overwrite and no file with the same name exists in the destination folder. I noticed this as well, and included a mention that the destination file has to already exist.

Of course, we can also wait until the bug is fixed before going forward with this ticket. 😄
